version: '3'

volumes:
  prod_postgres_data: {}
  prod_postgres_data_backups: {}
  prod_traefik: {}

services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_prod_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.prod/.django
      - ./.envs/.prod/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/prod/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_prod_postgres
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data:Z
      - prod_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.prod/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/prod/traefik/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_traefik
    depends_on:
      - django
    volumes:
      - prod_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      {%- if cookiecutter.use_celery == 'y' %}
      - "0.0.0.0:5555:5555"
      {%- endif %}

  redis:
    image: redis:5.0
  {%- if cookiecutter.use_celery == 'y' %}

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_prod_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_prod_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_prod_flower
    command: /start-flower

  {%- endif %}

  {% if cookiecutter.cloud_provider == 'AWS' %}
  awscli:
    build:
      context: .
      dockerfile: ./compose/prod/aws/Dockerfile
    env_file:
      - ./.envs/.prod/.django
    volumes:
      - production_postgres_data_backups:/backups:z
  {%- endif %}
